

services:
 mysqldb:
    image: mysql
    ports:
     - "${MYSQLDB_PORT}:${MYSQLDB_PORT}"
    expose:
     - "3306"
    environment:
      - MYSQLDB_PORT=${MYSQLDB_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - springboot-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s
      
 transfer-app:
    build:
      context: ./transfer-api
      dockerfile: Dockerfile    
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
     - "9081:9081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:${MYSQLDB_PORT}/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - springboot-mysql-network 

 wallet-app:
    build:
      context: ./wallet-api
      dockerfile: Dockerfile    
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
     - "9082:9082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:${MYSQLDB_PORT}/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - springboot-mysql-network 
      
 cancellation-app:
    build:
      context: ./cancellation-api
      dockerfile: Dockerfile    
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
     - "9083:9081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:${MYSQLDB_PORT}/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - springboot-mysql-network 

  produto-app:
    build:
      context: ./product-api
      dockerfile: Dockerfile    
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
     - "9083:9081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:${MYSQLDB_PORT}/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - springboot-mysql-network 
      
 gateway-app:
    build:
      context: ./gateway-api
      dockerfile: Dockerfile    
    
    ports:
     - "9085:9085"
   
    
volumes:
 db_data:
networks:
  springboot-mysql-network:
    name: springboot-mysql-network